# -*- coding: utf-8 -*-
"""IBM_HR_Attrition_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IqZFmuoSfLxPxTfWPMcZoVCKFaPDYD-Q

# IBM HR Attrition Analysis

## Phase 1: Database Setup & Schema

### 1.1. Import Libraries
"""

# Core Libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

# Display Settings (for better readability)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

"""### 1.2. Load Dataset"""

# Load dataset
df = pd.read_csv("HR-Employee-Attrition-Data.csv")

# Preview data
df.head()

"""### 1.3. Initial Structure Check"""

# Shape of dataset
df.shape

# Column names
df.columns

# Data types
df.dtypes

"""### 1.4. Schema Definition (Data Dictionary)"""

# Numerical Features
numerical_cols = [
    'Age', 'DailyRate', 'DistanceFromHome', 'Education',
    'EmployeeNumber', 'EnvironmentSatisfaction', 'HourlyRate',
    'JobInvolvement', 'JobLevel', 'JobSatisfaction',
    'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
    'PercentSalaryHike', 'PerformanceRating',
    'RelationshipSatisfaction', 'StockOptionLevel',
    'TotalWorkingYears', 'TrainingTimesLastYear',
    'WorkLifeBalance', 'YearsAtCompany',
    'YearsInCurrentRole', 'YearsSinceLastPromotion',
    'YearsWithCurrManager'
]

# Categorical Features
categorical_cols = [
    'Attrition', 'BusinessTravel', 'Department',
    'EducationField', 'Gender', 'JobRole',
    'MaritalStatus', 'OverTime'
]

# Constant / Drop Columns
drop_cols = ['EmployeeCount', 'Over18', 'StandardHours']

"""### 1.5. Drop Irrelevant Columns"""

df = df.drop(columns=drop_cols)

"""### 1.6. Data Type Optimization"""

for col in categorical_cols:
    df[col] = df[col].astype('category')

"""### 1.7. Data Integrity Checks"""

# Missing Values
df.isnull().sum()

# Duplicate Records
df.duplicated().sum()

# Logical Validation : Check invalid records (Critical for HR Data)
invalid_records = df[
    (df['YearsAtCompany'] > df['TotalWorkingYears']) |
    (df['YearsInCurrentRole'] > df['YearsAtCompany']) |
    (df['YearsWithCurrManager'] > df['YearsAtCompany'])
]

invalid_records.shape

"""### 1.8. Basic Statistical Summary"""

df.describe()

"""### 1.9. Final Schema Overview (Clean Dataset)"""

print("Final Shape:", df.shape)
print("\nCategorical Columns:\n", categorical_cols)
print("\nNumerical Columns:\n", numerical_cols)

"""## 📊 Phase 2: Data Understanding (EDA Foundation)"""

### 2.1. High-Level Overview

# Quick overview
df.info()

# Summary statistics
df.describe()

# Categorical summary
df.describe(include='category')

"""### 2.2. Attrition Baseline (MOST IMPORTANT STEP)"""

# Attrition count
df['Attrition'].value_counts()

# Attrition percentage
attrition_rate = df['Attrition'].value_counts(normalize=True) * 100
attrition_rate

# Visualisation
sns.countplot(x='Attrition', data=df)
plt.title("Attrition Distribution")
plt.show()

"""### 2.3. Demographic Understanding"""

# Age Distribution
sns.histplot(df['Age'], kde=True)
plt.title("Age Distribution")
plt.show()

# Gender Distribution
df['Gender'].value_counts(normalize=True) * 100

# Marital Status
df['MaritalStatus'].value_counts(normalize=True) * 100

"""### 2.4. Organizational Structure"""

# Department Distribution
df['Department'].value_counts()

# Job Role Distribution
df['JobRole'].value_counts()

"""### 2.5. Compensation Analysis (Initial View)"""

# Monthly Income
sns.histplot(df['MonthlyIncome'], kde=True)
plt.title("Monthly Income Distribution")
plt.show()

# Salary Hike
sns.histplot(df['PercentSalaryHike'], kde=True)
plt.title("Salary Hike Distribution")
plt.show()

"""### 2.6. Satisfaction Metrics"""

satisfaction_cols = [
    'JobSatisfaction', 'EnvironmentSatisfaction',
    'RelationshipSatisfaction', 'WorkLifeBalance'
]

for col in satisfaction_cols:
    sns.countplot(x=col, data=df)
    plt.title(f"{col} Distribution")
    plt.show()

"""### 2.7. Experience & Tenure"""

# Total Working Years
sns.histplot(df['TotalWorkingYears'], kde=True)
plt.show()

# Years at Company
sns.histplot(df['YearsAtCompany'], kde=True)
plt.show()

"""### 2.8. Work Behavior"""

# Overtime
df['OverTime'].value_counts(normalize=True) * 100

# Distance from Home
sns.histplot(df['DistanceFromHome'], kde=True)
plt.show()

"""### 2.9. Correlation Analysis (Numerical Only)  """

# Select only numeric columns
numeric_df = df.select_dtypes(include=['int64', 'float64'])

# Correlation heatmap
plt.figure(figsize=(12,8))
sns.heatmap(numeric_df.corr(), cmap='coolwarm')
plt.title("Correlation Heatmap (Numerical Features Only)")
plt.show()

plt.figure(figsize=(12,8))
sns.heatmap(df[numerical_cols].corr(), cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()

plt.figure(figsize=(14,10))
corr = numeric_df.corr()

sns.heatmap(
    corr,
    cmap='coolwarm',
    center=0,
    square=True
)

plt.title("Correlation Heatmap")
plt.show()

"""### 2.10. Initial Observations (Critical Thinking)

From this phase, you should conclude:

🔹 Workforce Profile

Young to mid-age workforce

Majority early-career employees

🔹 Compensation

Income highly skewed

Clear hierarchy by job level

🔹 Satisfaction

Mostly average satisfaction

Few highly dissatisfied employees

🔹 Risk Indicators (Hypothesis)

Overtime

Low tenure

Lower income

Mid satisfaction levels

### 2.11. Hypothesis Formation (VERY IMPORTANT)
Employees working overtime are more likely to leave?

Lower income employees have higher attrition?

Early tenure employees (0–2 years) leave more?

Low satisfaction leads to attrition?

Sales department has higher attrition?

## Phase 3: Feature Engineering

3.1. Attrition Encoding (Target Variable)
"""

# Convert Attrition to binary
df['Attrition_Flag'] = df['Attrition'].map({'Yes': 1, 'No': 0})

"""### 3.2. Income-Based Features"""

# Income per Job Level
df['Income_Per_Level'] = df['MonthlyIncome'] / df['JobLevel']

# Income vs Experience
df['Income_Per_YearExp'] = df['MonthlyIncome'] / (df['TotalWorkingYears'] + 1)

"""### 3.3. Tenure-Based Features"""

# Tenure Ratio
df['Tenure_Ratio'] = df['YearsAtCompany'] / (df['TotalWorkingYears'] + 1)

# Promotion Gap
df['Promotion_Gap'] = df['YearsSinceLastPromotion']

# Role Stability
df['Role_Stability'] = df['YearsInCurrentRole'] / (df['YearsAtCompany'] + 1)

"""### 3.4. Work-Life & Effort Features"""

# Overtime Flag
df['OverTime_Flag'] = df['OverTime'].map({'Yes': 1, 'No': 0})

# Work Stress Index (Composite Feature)
df['Work_Stress_Index'] = (
    df['JobInvolvement'].astype(int) +
    df['OverTime_Flag'].astype(int) +
    (5 - df['WorkLifeBalance'].astype(int))
)

"""### 3.5. Satisfaction Score (Composite Feature)"""

df['Satisfaction_Score'] = (
    df['JobSatisfaction'] +
    df['EnvironmentSatisfaction'] +
    df['RelationshipSatisfaction'] +
    df['WorkLifeBalance']
)

"""### 3.6. Commute Burden"""

df['Commute_Intensity'] = df['DistanceFromHome'] * df['OverTime_Flag'].astype(int)

"""### 3.7. Career Growth Features"""

# Growth Rate
df['Career_Growth_Rate'] = df['JobLevel'] / (df['TotalWorkingYears'] + 1)

# Companies per Year
df['Companies_Per_Year'] = df['NumCompaniesWorked'] / (df['TotalWorkingYears'] + 1)

"""### 3.8. Age Group Segmentation"""

df['Age_Group'] = pd.cut(
    df['Age'],
    bins=[18, 25, 35, 45, 60],
    labels=['18-25', '26-35', '36-45', '46+']
)

"""### 3.9. Experience Group Segmentation"""

df['Experience_Group'] = pd.cut(
    df['TotalWorkingYears'],
    bins=[0, 5, 10, 20, 40],
    labels=['0-5', '6-10', '11-20', '20+']
)

"""### 3.10. Validation Check (Very Important)"""

df.head()
df.info()

"""## 📊 Phase 4: Univariate Analysis (Deep Feature Insights)

### 4.1. Target Variable Analysis (Attrition)
"""

# Distribution
df['Attrition'].value_counts(normalize=True) * 100

sns.countplot(x='Attrition', data=df)
plt.title("Attrition Distribution")
plt.show()

"""### 4.2. Numerical Features Distribution"""

# General Distribution Function (Reusable)
def plot_distribution(col):
    fig, axes = plt.subplots(1, 2, figsize=(12,4))

    sns.histplot(df[col], kde=True, ax=axes[0])
    axes[0].set_title(f"{col} Distribution")

    sns.boxplot(x=df[col], ax=axes[1])
    axes[1].set_title(f"{col} Boxplot")

    plt.show()

# Key Features to Analyse
key_numeric_cols = [
    'Age', 'MonthlyIncome', 'DistanceFromHome',
    'TotalWorkingYears', 'YearsAtCompany',
    'Work_Stress_Index', 'Satisfaction_Score'
]

for col in key_numeric_cols:
    plot_distribution(col)

"""### 4.3. Categorical Features Distribution"""

# General Function
def plot_count(col):
    plt.figure(figsize=(6,4))
    sns.countplot(x=col, data=df)
    plt.title(f"{col} Distribution")
    plt.xticks(rotation=45)
    plt.show()

# Key Categorical Columns
cat_cols = [
    'Gender', 'Department', 'JobRole',
    'MaritalStatus', 'OverTime',
    'BusinessTravel', 'EducationField'
]

for col in cat_cols:
    plot_count(col)

"""### 4.4. Ordinal Feature Analysis"""

ordinal_cols = [
    'JobSatisfaction', 'EnvironmentSatisfaction',
    'WorkLifeBalance', 'JobInvolvement'
]

for col in ordinal_cols:
    sns.countplot(x=col, data=df)
    plt.title(f"{col} Distribution")
    plt.show()

"""### 4.5. Outlier Detection (Critical)"""

for col in ['MonthlyIncome', 'TotalWorkingYears']:
    sns.boxplot(x=df[col])
    plt.title(f"{col} Outliers")
    plt.show()

"""### 4.6. Skewness Analysis"""

df[key_numeric_cols].skew()

"""### Find Low Satisfaction_Score"""

# Thresholds
low_satisfaction_threshold = df['Satisfaction_Score'].quantile(0.25)
high_stress_threshold = df['Work_Stress_Index'].quantile(0.75)
low_tenure_threshold = df['YearsAtCompany'].quantile(0.25)
low_income_threshold = df['MonthlyIncome'].quantile(0.25)

low_satisfaction_threshold, high_stress_threshold, low_tenure_threshold, low_income_threshold

# 1. Low Satisfaction Employees
low_satisfaction = df[df['Satisfaction_Score'] <= low_satisfaction_threshold]

low_satisfaction[['Satisfaction_Score', 'Attrition']].head()

# 2. High Stress Employees
high_stress = df[df['Work_Stress_Index'] >= high_stress_threshold]

# 3. Low Tenure Employees
low_tenure = df[df['YearsAtCompany'] <= low_tenure_threshold]

# 4. Low Income Employees
low_income = df[df['MonthlyIncome'] <= low_income_threshold]

# Measure Attrition Rate in Each Segment
def attrition_rate(segment, name):
    rate = segment['Attrition_Flag'].astype(int).mean() * 100
    print(f"{name} Attrition Rate: {rate:.2f}%")

attrition_rate(low_satisfaction, "Low Satisfaction")
attrition_rate(high_stress, "High Stress")
attrition_rate(low_tenure, "Low Tenure")
attrition_rate(low_income, "Low Income")

# Identify High-Risk Combined Segment
high_risk_group = df[
    (df['Satisfaction_Score'] <= low_satisfaction_threshold) &
    (df['Work_Stress_Index'] >= high_stress_threshold) &
    (df['YearsAtCompany'] <= low_tenure_threshold) &
    (df['MonthlyIncome'] <= low_income_threshold)
]

high_risk_group.shape

# 📊 Attrition Rate of High-Risk Group
attrition_rate(high_risk_group, "High Risk Combined Group")

"""## Phase 5: Bivariate Analysis (Attrition vs Features)

### 5.1. Attrition vs Categorical Variables
"""

# Function for Analysis
def attrition_by_category(col):
    result = pd.crosstab(df[col], df['Attrition'], normalize='index') * 100
    print(f"\nAttrition % by {col}:\n", result)

    sns.countplot(x=col, hue='Attrition', data=df)
    plt.title(f"Attrition by {col}")
    plt.xticks(rotation=45)
    plt.show()

# Key Variables
cat_analysis_cols = [
    'OverTime', 'Department', 'JobRole',
    'MaritalStatus', 'BusinessTravel'
]

for col in cat_analysis_cols:
    attrition_by_category(col)

"""### 5.2. Statistical Test (Categorical → Chi-Square)"""

from scipy.stats import chi2_contingency

def chi_square_test(col):
    table = pd.crosstab(df[col], df['Attrition'])
    chi2, p, dof, expected = chi2_contingency(table)

    print(f"{col} → p-value: {p:.5f}")

for col in cat_analysis_cols:
    chi_square_test(col)

"""### 5.3. Attrition vs Numerical Variables"""

# Visualisation
def boxplot_attrition(col):
    sns.boxplot(x='Attrition', y=col, data=df)
    plt.title(f"{col} vs Attrition")
    plt.show()

num_analysis_cols = [
    'MonthlyIncome', 'YearsAtCompany',
    'Work_Stress_Index', 'Satisfaction_Score'
]

for col in num_analysis_cols:
    boxplot_attrition(col)

"""### 5.4. Statistical Test (Numerical → T-Test)"""

from scipy.stats import ttest_ind

def t_test(col):
    group_yes = df[df['Attrition_Flag'] == 1][col]
    group_no = df[df['Attrition_Flag'] == 0][col]

    t_stat, p = ttest_ind(group_yes, group_no)
    print(f"{col} → p-value: {p:.5f}")

for col in num_analysis_cols:
    t_test(col)

"""### 5.5. Effect Size (VERY IMPORTANT 🔥)"""

# Cohen’s d
def cohens_d(col):
    group1 = df[df['Attrition_Flag'] == 1][col]
    group2 = df[df['Attrition_Flag'] == 0][col]

    mean_diff = group1.mean() - group2.mean()
    pooled_std = np.sqrt((group1.std()**2 + group2.std()**2) / 2)

    d = mean_diff / pooled_std
    print(f"{col} → Cohen's d: {d:.3f}")

for col in num_analysis_cols:
    cohens_d(col)

"""## Phase 6: Attrition Driver Ranking (Statistical + ML)

### 6.1. Data Preparation
"""

# Select Features
features = [
    'MonthlyIncome', 'YearsAtCompany',
    'Work_Stress_Index', 'Satisfaction_Score',
    'OverTime_Flag', 'JobLevel',
    'TotalWorkingYears', 'Age'
]

X = df[features]
y = df['Attrition_Flag']

# Train-Test Split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Scaling (for Logistic Regression)
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

"""### 6.2. Logistic Regression (Interpretability Model)"""

from sklearn.linear_model import LogisticRegression

log_model = LogisticRegression()
log_model.fit(X_train_scaled, y_train)

# Coefficients (Driver Strength)
log_importance = pd.DataFrame({
    'Feature': features,
    'Coefficient': log_model.coef_[0]
}).sort_values(by='Coefficient', key=abs, ascending=False)

log_importance

"""### 6.3 Random Forest (Non-Linear Model)"""

from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X_train, y_train)

# Feature Importance
rf_importance = pd.DataFrame({
    'Feature': features,
    'Importance': rf_model.feature_importances_
}).sort_values(by='Importance', ascending=False)

rf_importance

"""### 6.4 Model Evaluation"""

from sklearn.metrics import classification_report

y_pred = rf_model.predict(X_test)
print(classification_report(y_test, y_pred))

"""### 6.5 Combine Rankings (Final Driver Score)"""

# Normalize values
log_importance['Abs_Coeff'] = log_importance['Coefficient'].abs()

combined = log_importance.merge(rf_importance, on='Feature')

combined['Final_Score'] = (
    combined['Abs_Coeff'] / combined['Abs_Coeff'].max() +
    combined['Importance'] / combined['Importance'].max()
)

final_ranking = combined.sort_values(by='Final_Score', ascending=False)

final_ranking

"""### 6.6 Top 10 Attrition Drivers

| Rank | Feature            | Impact        |
| ---- | ------------------ | ------------- |
| 1    | MonthlyIncome      | 🔴 Very High  |
| 2    | Satisfaction_Score | 🔴 Very High  |
| 3    | YearsAtCompany     | 🔴 High       |
| 4    | OverTime_Flag      | 🔴 High       |
| 5    | Work_Stress_Index  | 🟠 Medium     |
| 6    | TotalWorkingYears  | 🟠 Medium     |
| 7    | JobLevel           | 🟠 Medium     |
| 8    | Age                | 🟡 Low-Medium |

### 6.7 Feature Importance Visualization
"""

import matplotlib.pyplot as plt

plt.figure(figsize=(10,6))
plt.barh(final_ranking['Feature'], final_ranking['Final_Score'])
plt.gca().invert_yaxis()
plt.title("Top Attrition Drivers")
plt.xlabel("Importance Score")
plt.show()

"""### 6.8 Key Business Interpretation

🔴 Core Drivers

Compensation (MonthlyIncome)

Satisfaction (Satisfaction_Score)

Tenure (YearsAtCompany)

🟠 Behavioral Drivers

Overtime

Work Stress

🟡 Structural Drivers

Job Level

Experience

Age

### 6.9. Power BI Ready Metrics Layer
"""

# Export Dataset
df.to_csv("HR_Attrition_Engineered.csv", index=False)

# Create Driver Table for Dashboard
final_ranking.to_csv("Attrition_Driver_Ranking.csv", index=False)

# Power BI – Metrics Layer
df.to_csv("HR_Attrition_Final.csv", index=False)
final_ranking.to_csv("Attrition_Driver_Ranking.csv", index=False)